# Generated by Django 3.0.1 on 2021-03-30 17:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/HomeBanner/')),
                ('slug', models.SlugField(allow_unicode=True, editable=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('alternative_text', models.CharField(default='', editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('company', models.CharField(default='Texile Ltd', max_length=128)),
                ('category', models.CharField(choices=[('SAREE', 'SAREE'), ('SUIT', 'SUIT'), ('KURTI', 'KURTI')], max_length=200)),
                ('sub_category', models.CharField(choices=[('Mens', 'Men'), ('Womens', 'Women'), ('Kids', 'Kids')], default='', max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('alternative_text', models.CharField(default='', editable=False, max_length=200)),
                ('size_5XL', models.IntegerField(default=0)),
                ('size_4XL', models.IntegerField(default=0)),
                ('size_3XL', models.IntegerField(default=0)),
                ('size_XXL', models.IntegerField(default=0)),
                ('size_XL', models.IntegerField(default=0)),
                ('size_L', models.IntegerField(default=0)),
                ('size_M', models.IntegerField(default=0)),
                ('size_S', models.IntegerField(default=0)),
                ('size_XS', models.IntegerField(default=0)),
                ('size_XXS', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0, editable=False)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_by_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('discount_by_value', models.IntegerField(blank=True, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default_profile_pic/default-profile.jpg', upload_to='images/UserProfile/')),
                ('alternative_text', models.CharField(editable=False, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Commerce.UserProfile')),
            ],
        ),
    ]
